# Generated by Django 5.2.5 on 2025-08-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100)),
                ('chat_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=10)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('file_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
