# Generated by Django 5.2.5 on 2025-08-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tag',
            new_name='api_tag_categor_6f24bb_idx',
            old_name='api_tag_category_8b2c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='api_tag_is_acti_88f219_idx',
            old_name='api_tag_is_activ_2c8c8c_idx',
        ),
    ]
