# Generated by Django 5.2.5 on 2025-08-23 16:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0008_rename_api_tag_category_8b2c8c_idx_api_tag_categor_6f24bb_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                (
                    "color_bg",
                    models.CharField(
                        help_text="Tailwind CSS background color class", max_length=20
                    ),
                ),
                (
                    "color_text",
                    models.CharField(
                        help_text="Tailwind CSS text color class", max_length=20
                    ),
                ),
                (
                    "color_border",
                    models.CharField(
                        help_text="Tailwind CSS border color class", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of priority level"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order for display purposes"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Priorities",
                "ordering": ["sort_order", "priority"],
            },
        ),
        migrations.CreateModel(
            name="ActivityStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                (
                    "color_bg",
                    models.CharField(
                        help_text="Tailwind CSS background color class", max_length=20
                    ),
                ),
                (
                    "color_text",
                    models.CharField(
                        help_text="Tailwind CSS text color class", max_length=20
                    ),
                ),
                (
                    "color_border",
                    models.CharField(
                        help_text="Tailwind CSS border color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon representation", max_length=10
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this status means"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order for display purposes"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Statuses",
                "ordering": ["sort_order", "status"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Production", "Production"),
                            ("Maintenance", "Maintenance"),
                            ("Inspection & Audit", "Inspection & Audit"),
                            ("Engineering", "Engineering"),
                            ("Logistics", "Logistics"),
                            ("Quality", "Quality"),
                            ("Meetings", "Meetings"),
                            ("Projects", "Projects"),
                            ("Training", "Training"),
                            ("Admin & Systems", "Admin & Systems"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("assigned_to", models.CharField(max_length=100)),
                ("assigned_by", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Estimated duration in minutes"),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="api.activitypriority",
                    ),
                ),
                (
                    "status_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="api.activitystatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
