# Generated by Django 5.2.5 on 2025-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="maternal_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="mobile",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
