# Generated by Django 5.2.5 on 2025-09-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="secondary_phone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="mobile",
                max_length=10,
                null=True,
            ),
        ),
    ]
