# Generated by Django 5.2.5 on 2025-09-05 17:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_userprofile_secondary_phone_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategoryNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="📋", max_length=10)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Activity Categories (New)",
                "db_table": "api_activitycategory",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityPriorityNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=0)),
                ("color_bg", models.CharField(default="#F3F4F6", max_length=7)),
                ("color_text", models.CharField(default="#374151", max_length=7)),
                ("color_border", models.CharField(default="#D1D5DB", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Activity Priorities (New)",
                "db_table": "api_activitypriority_new",
                "ordering": ["-level"],
            },
        ),
        migrations.CreateModel(
            name="ActivityStatusNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("color_bg", models.CharField(default="#F3F4F6", max_length=7)),
                ("color_text", models.CharField(default="#374151", max_length=7)),
                ("color_border", models.CharField(default="#D1D5DB", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Activity Statuses (New)",
                "db_table": "api_activitystatus_new",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="NewsCategoryNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="📰", max_length=10)),
                ("color", models.CharField(default="#10B981", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "News Categories (New)",
                "db_table": "api_newscategory",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="NewsStatusNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("color_bg", models.CharField(default="#F3F4F6", max_length=7)),
                ("color_text", models.CharField(default="#374151", max_length=7)),
                ("color_border", models.CharField(default="#D1D5DB", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "News Statuses (New)",
                "db_table": "api_newsstatus",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityNew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Estimated duration in minutes"),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                ("assigned_to", models.CharField(max_length=100)),
                ("assigned_by", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="api.activitycategorynew",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="api.activityprioritynew",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="api.activitystatusnew",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities (New)",
                "db_table": "api_activity_new",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="api_activit_categor_356db9_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="api_activit_status__bd69f6_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="api_activit_created_7926a2_idx",
                    ),
                    models.Index(
                        fields=["is_active", "start_time"],
                        name="api_activit_is_acti_bdc1e0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsUpdateNew",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("tags", models.JSONField(default=list)),
                ("icon", models.CharField(default="📰", max_length=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("priority", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates",
                        to="api.newscategorynew",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_updates_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates",
                        to="api.newsstatusnew",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News Updates (New)",
                "db_table": "api_newsupdate",
                "ordering": ["-priority", "-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="api_newsupd_categor_ca75ac_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="api_newsupd_status__d5e9c0_idx",
                    ),
                    models.Index(
                        fields=["created_by", "timestamp"],
                        name="api_newsupd_created_0b9dcc_idx",
                    ),
                    models.Index(
                        fields=["is_active", "timestamp"],
                        name="api_newsupd_is_acti_6cff23_idx",
                    ),
                    models.Index(
                        fields=["priority", "timestamp"],
                        name="api_newsupd_priorit_24974c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UpdateBookmark",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="api.update",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("update", "user")},
            },
        ),
    ]
