# Generated by Django 5.2.5 on 2025-09-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_activitycategorynew_activityprioritynew_and_more"),
    ]

    operations = []
