# Generated by Django 5.2.5 on 2025-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20250905_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
