# Generated by Django 5.2.5 on 2025-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_sync_user_profile_fields_with_frontend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_country_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="secondary_phone_country_code",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
