# Generated by Django 5.2.5 on 2025-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_rename_phone_country_codes"),
    ]

    operations = [
        # Rename phone fields to match frontend naming convention
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone",
            new_name="phone1",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="primary_country_code",
            new_name="phonecc1",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone_type",
            new_name="phonet1",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="secondary_phone",
            new_name="phone2",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="secondary_country_code",
            new_name="phonecc2",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="secondary_phone_type",
            new_name="phonet2",
        ),
    ]
