# Generated by Django 5.2.5 on 2025-09-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_phone_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone1",
            field=models.CharField(
                blank=True, help_text="Primary phone number", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone2",
            field=models.CharField(
                blank=True, help_text="Secondary phone number", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phonecc1",
            field=models.CharField(
                blank=True,
                default="+1",
                help_text="Primary phone country code",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phonecc2",
            field=models.CharField(
                blank=True,
                help_text="Secondary phone country code",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phonet1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="mobile",
                help_text="Primary phone type",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phonet2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                help_text="Secondary phone type",
                max_length=10,
                null=True,
            ),
        ),
    ]
