# Generated by Django 5.2.5 on 2025-09-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_user_profile_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="street_address",
            new_name="street",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="apartment_suite",
            new_name="apartment",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="state_province",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="zip_code",
            new_name="zipcode",
        ),
    ]
