# Generated by Django 5.2.5 on 2025-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_rename_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zipcode_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
