# Generated by Django 5.2.5 on 2025-09-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_add_location_id_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="city_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="zipcode_id",
        ),
    ]
